### ISSUE TITLE
Cannot reproduce the results using the model provided

### ISSUE THREAD

**Issue by CCYChongyanChen** [Ien001/AG-CNN#5]
Hi, thank you for making this work open source.
I just downloaded the model you provided from Google drive and place it in the best_model folder, changed the path for test.py and run test.py. However, the accuracy I got is around 0.51.  Could you help me to check if there is anything wrong with my process? Thank you!
![image](https://user-images.githubusercontent.com/21120604/95710681-cfd40000-0c26-11eb-9e9b-5f2b0d86767d.png)

**Comment by Ien001** [comment]
@CCYChongyanChen 
Hi,

Thanks for your post!

I am not sure where the problem is because the AUC is really low, but you can try this:

1. Redownload models, and run `test.py` again. See how it works.

2. if 1 not works, you can try to train your own model and see if you can get a similar result.

Also, remember to have the complete dataset, it's quite large I remember.

If still not work, you are welcomed to leave comments and I can try to help!

Best.
Ian

**Comment by CCYChongyanChen** [comment]
Hi @len001,
Thank you a lot for replying! I also trained it myself and got around AUC=0.67
![image](https://user-images.githubusercontent.com/21120604/96700275-e1b75080-1354-11eb-9bd9-02dc953d4cdf.png)

**Comment by Ien001** [comment]
> Hi @len001,
> Thank you a lot for replying! I also trained it myself and got around AUC=0.67
> ![image](https://user-images.githubusercontent.com/21120604/96700275-e1b75080-1354-11eb-9bd9-02dc953d4cdf.png)

Hi @CCYChongyanChen ,
Thanks for your posting. 
I think you can try to change the learning rate for 3 different model dynamically to have better performance.
Best.

**Comment by Yajie-Zhang** [comment]
> Hi, thank you for making this work open source. I just downloaded the model you provided from Google drive and place it in the best_model folder, changed the path for test.py and run test.py. However, the accuracy I got is around 0.51. Could you help me to check if there is anything wrong with my process? Thank you! ![image](https://user-images.githubusercontent.com/21120604/95710681-cfd40000-0c26-11eb-9e9b-5f2b0d86767d.png)

Hi, if you have solved this problem you mentioned above? I met the same problem.
